### ISSUE TITLE
Is emacs-26.1 really a requirement here?

### ISSUE THREAD

**Issue by michaelsjackson** [alphapapa/org-make-toc#11]
This disqualifies my emacs-25.3

**Comment by alphapapa** [comment]
I don't know.  I don't have time to build and install 2-years-old Emacs versions and test my packages on all the combinations of old package versions that might entail.  If you want to try it yourself, it would be very simple and quick to do so.

**Comment by michaelsjackson** [comment]
How can I install incompatible package after list-packages? i does not work.

**Comment by alphapapa** [comment]
You could install or evaluate the source code file manually.

**Comment by michaelsjackson** [comment]
Thanks, I have seen also ways how multiple emacs can be installed independently of each other, I guess in future I should use this method, for all experiments trying a separate one, only after enough testing, if all works, I can switch over to that version, or just for experimenting, trying various emacs variantls ...
