### ISSUE TITLE
whitespace before :CONTENTS: and :END: drawer markers regexp failure

### ISSUE THREAD

**Issue by progfolio** [alphapapa/org-make-toc#17]
fixed by #15

**Comment by nullman** [comment]
I'm also experiencing this issue as my org setup has drawer markets indented at my heading level.  Example:

```org
* Table of Contents
  :PROPERTIES:
  :TOC: :include all
  :END:

  :CONTENTS:
  :END:
```

Please change the regexp for drawer markers to account for white space at the line start.  Thanks.

**Comment by alphapapa** [comment]
Thanks.

**Comment by alphapapa** [comment]
@nullman Should be fixed now.  Thanks.
