### ISSUE TITLE
update readme with installation instructions for MELPA

### ISSUE THREAD

**Issue by japhir** [alphapapa/org-make-toc#18]
Seems like a lovely package! I found out it's on melpa already after initially not trying out the package because I didn't feel like using straight.el or copy-pasting stuff to local files. Maybe other users have a similar issue :)

**Comment by alphapapa** [comment]
I don't understand.  The readme indicates that it can be installed from MELPA.

**Comment by japhir** [comment]
Me neither, looks like past me had a brainfart? Or perhaps he wanted a simple `(use-package org-make-toc :ensure t)` in there or something… Let's ignore him ;-).

**Comment by alphapapa** [comment]
:)  Anyway, I don't recommend using `:ensure t`, and I prefer not to offer how-to-install-Emacs-packages instructions in every one of my projects' readmes.  Rather, users should refer to the appropriate general documentation.  Thanks.

**Comment by japhir** [comment]
just curious, why do you recommend against using `:ensure t`? I can imagine b/c it'll make your init script very slow the first time on a brand new emacs install?

**Comment by alphapapa** [comment]
I don't generally recommend installing or updating any packages automatically.  Of course, many users do, and they seem to be happy with it.  But I prefer to install and update packages manually.  This way, I don't encounter undesired changes introduced by newer versions until I'm ready to deal with them.  I also store installed packages in git with the rest of my Emacs config, so I can easily roll back to known-good configurations and package versions.

I don't often set up a new Emacs config from scratch.  When I install Emacs on a new system, I clone my config, which includes all the installed packages (which also means that I can reproduce my entire config at any time, even if ELPA or MELPA are down).  This way, I don't have different versions of packages on different systems, which can easily become a mess.  

If I need to use a different Emacs config or test in a clean one, I use https://github.com/alphapapa/emacs-sandbox.sh, which makes it easy.

For more info, see the many and frequent discussions on r/emacs, some of which I've posted more explanations (opinions) in.  :)

**Comment by alphapapa** [comment]
Yes, and I said, "I don't generally recommend installing or updating any packages automatically."
