### ISSUE TITLE
Add option to make links work in both Github and Emacs org mode by inserting Custom Id property

### ISSUE THREAD

**Issue by hemanta212** [alphapapa/org-make-toc#20]
Hi, 
If a custom id is inserted into the property drawer in each heading. The links will work in Org-mode. So it might be desirable for some users to get this behaviour where the tool inserts the CUSTOM ID property in each heading. Any thoughts on this?

For my use case I generally have a lot of properties customization inside my headings already so one line of CUSTOM ID won't hurt instead of me manually having to put it in each heading.

**Comment by alphapapa** [comment]
Hi,

I haven't tested that solution, but if it works, I've no objection to supporting it in this package.  I'm not sure if I would use it, so I don't know if I'd code it myself anytime soon.

**Comment by hemanta212** [comment]
Custom id links implementation is addition on top of existing way, With current way we have support for github but not org mode. Additing custom id links will enable the links to work on org mode. Thus, supporting both github and org-mode.

**Comment by noctuid** [comment]
Ah, I was thinking of UUID/normal ID links.  This approach seems to work fine.  I opened a PR.

**Comment by hemanta212** [comment]
Can confirm, it works great!, Thank you so much @alphapapa and @noctuid 🙏

**Comment by alphapapa** [comment]
@hemanta212 Thanks.
