### ISSUE TITLE
void-function pos-eol

### ISSUE THREAD

**Issue by VladimirAlexiev** [alphapapa/org-make-toc#29]
`org-make-toc--replace-entry-contents` causes this error: `void-function pos-eol`.
This happened after upgrading `org`.

Versions:
- org-version "9.6.19"
- emacs-version "28.1"
- org-make-toc Version: 0.6-pre

**Comment by VladimirAlexiev** [comment]
https://www.gnu.org/software/emacs/manual/html_node/elisp/Text-Lines.html#index-pos_002deol documents such function for Emacs version 29.2.
It also says "Like line-end-position, but ignores fields (and is more efficient)."

**Comment by alphapapa** [comment]
Hello Vladimir,

> `org-make-toc--replace-entry-contents` causes this error: `void-function pos-eol`. This happened after upgrading `org`.

I don't understand why this error would begin happening after you upgraded the `org` package; that should not have any effect on this issue.

Anyway, the use of `pos-eol` in this package is covered by its depending on the `compat` package.  If you look in its file `compat-29.el` you'll see these:
```el
(compat-defun pos-bol (&optional n) ;; <compat-tests:pos-bol>
  "Return the position of the first character on the current line.
With optional argument N, scan forward N - 1 lines first.
If the scan reaches the end of the buffer, return that position.

This function ignores text display directionality; it returns the
position of the first character in logical order, i.e. the smallest
character position on the logical line.  See `vertical-motion' for
movement by screen lines.

This function does not move point.  Also see `line-beginning-position'."
  (declare (side-effect-free t))
  (let ((inhibit-field-text-motion t))
    (line-beginning-position n)))

(compat-defun pos-eol (&optional n) ;; <compat-tests:pos-bol>
  "Return the position of the last character on the current line.
With argument N not nil or 1, move forward N - 1 lines first.
If scan reaches end of buffer, return that position.

This function ignores text display directionality; it returns the
position of the last character in logical order, i.e. the largest
character position on the line.

This function does not move point.  Also see `line-end-position'."
  (declare (side-effect-free t))
  (let ((inhibit-field-text-motion t))
    (line-end-position n)))
```
If you are seeing this error, you likely have an incorrect installation of `compat` or something else like that.

**Comment by VladimirAlexiev** [comment]
Hi @alphapapa ! I have compat-29.1.4.4, and I see your module has this in the beginning:
```
;; Package-Requires: ((emacs "26.1") (dash "2.12") (s "1.10.0") (org "9.3") (compat "29.1"))
```

But shouldn't you also have `(require 'compat-29)` ?

**Comment by alphapapa** [comment]
> But shouldn't you also have `(require 'compat-29)` ?

According to Compat's manual, `(require 'compat)` is all that's needed.  It's surprising that the library is not being loaded already by something else in your config, but I guess it isn't.

I pushed a fix for this to `master`.  Thanks for reporting it.
