### ISSUE TITLE
Allow code in TOC

### ISSUE THREAD

**Issue by asos-stephanemaniaci** [alphapapa/org-make-toc#3]
First of all thanks for the package it's helped me a lot.

I was wondering if it would be possible to have code headings also appear as code in the TOC?

```
* Introduction
** API
*** ~someMethod~
*** ~someOtherMethod~
```

When I generate the TOC and push it to GitHub, the headings are correctly preformatted but the TOC still sports the `~`. Any chance to parse these?

**Comment by alphapapa** [comment]
Hi, glad to hear it's been useful for you.

I think that's a problem with GitHub's Org renderer, which has several issues like that that need to be fixed.  But we could add a workaround for it, probably. I'll look into it when I get a chance. Thanks.

**Comment by alphapapa** [comment]
Oops, I fixed this in https://github.com/alphapapa/org-make-toc/commit/be4c1f863b5cc152ab60b967a6f753030c7b4e5a but forgot to close this issue.  @asos-stephanemaniaci Please let me know if this fixes it for you!
